## Video
profile=high-quality

## Behavior (personal preference)
keep-open=yes
save-position-on-quit

## Screenshots
screenshot-format=png
screenshot-dir="~/Pictures/mpv"
screenshot-template="%F-%p-%n"
screenshot-high-bit-depth=no

## Language Priority
## Sub
## Add enm before eng for honorifics
slang=eng,en
alang=jpn,ja

## Dub
#slang=zxx,eng,en
#alang=eng,en
#subs-with-matching-audio=forced

osc=no
border=no #optional - if you don't want to see the OS border
